Feature/50/cohere unit tests
llm-proxy/llm-proxy pull request #105
Opened 2023-11-19 04:18 UTC by dinuja9

- Finished unit tests based off current cohere code in main branch

2023-11-24 20:23 UTC, laxitshahi commented on llmproxy/tests/unit_tests/models/test_cohere.py
> +cohere_api_key = "iqAm7dJ9TEOwxFSetAfkurVyPjFLwlyQVo0Xd5oe"
We can't push API keys like this

2023-11-24 20:23 UTC, BallenAlain commented on llmproxy/tests/unit_tests/models/test_cohere.py
> +cohere_api_key = "iqAm7dJ9TEOwxFSetAfkurVyPjFLwlyQVo0Xd5oe"
my bad didn't know the comment was pending

2023-11-25 10:03 UTC, laxitshahi requested changes
conflicts

2023-11-25 22:09 UTC, laxitshahi approved these changes

2023-11-25 22:13 UTC, laxitshahi approved these changes

2023-11-25 22:15 UTC, TheVicBro approved these changes

2023-11-25 22:15 UTC, merged