Fixed model structure naming
llm-proxy/llm-proxy pull request #107
Opened 2023-11-25 04:28 UTC by TheVicBro

Separated yamls
Refactored model naming scheme

2023-11-25 10:19 UTC, laxitshahi requested changes
- Unit tests are failing, you have to refactor them accordingly
- We need to discuss alternative solution (ABCs hierarchy)

2023-11-25 10:19 UTC, laxitshahi commented on developer_configuration.yml
File should be inside library, out of user's easy reach. Is there also a way to make it read only?

2024-01-17 22:00 UTC, laxitshahi requested changes

2024-01-17 22:44 UTC, TheVicBro commented on llmproxy/llmproxy.py
> +        path_to_user_configuration: str = "api_configuration.yml",
renamed to internal_configuration.yml and placed within llmproxy/config

2024-01-17 22:45 UTC, TheVicBro commented on llmproxy/provider/base.py
> +class BaseModel(ABC):
done

2024-01-17 22:45 UTC, TheVicBro commented on llmproxy/provider/openai/chatgpt.py
> +
refactored models didnt have new changes from git merge since they were moved, should be fixed now

2024-01-17 22:46 UTC, TheVicBro commented on developer_configuration.yml
don't think there's a way to make it read-only, moved it to a new config folder in llmproxy. will leave this open in case we want to take another look

2024-01-18 05:24 UTC, laxitshahi approved these changes

2024-01-18 05:59 UTC, merged