bugfix/121/unit test fix
llm-proxy/llm-proxy pull request #124
Opened 2024-01-19 21:48 UTC by DesNahback

#121
remove unnecessary yaml file and fix current unit tests

2024-01-19 23:52 UTC, BallenAlain approved these changes
lgtm :shipit:

2024-01-20 01:06 UTC, laxitshahi requested changes

2024-01-20 04:43 UTC, DesNahback commented on llmproxy/tests/unit_tests/llmproxy_client/test_llmproxy.py
> +    user_setting = _get_settings_from_yml(path_to_yml="llmproxy.config.yml")
its not unnecessary as its just testing the _get_settings_from_yml function so if there's error when getting the setting from llmproxy.config.yml or internal.config.yml running pytest will failed the test

2024-01-20 04:49 UTC, BallenAlain commented on llmproxy/tests/unit_tests/llmproxy_client/test_llmproxy.py
>  def test_setup_user_models() -> None:
load_dotenv isn't being called in the init function of LLMProxy
<img width="732" alt="Screenshot 2024-01-19 at 11 49 12 PM" src="https://github.com/llm-proxy/llm-proxy/assets/46403906/cd5da3eb-bfec-4aef-b8d1-a7141524ca5b">

maybe test_llmproxy isnt initializing the class properly?

2024-01-20 05:04 UTC, BallenAlain commented on llmproxy/tests/unit_tests/llmproxy_client/test_llmproxy.py
>  def test_setup_user_models() -> None:
i initialized the LLMProxy class in the unit test file

2024-01-20 07:11 UTC, laxitshahi requested changes

2024-01-20 07:11 UTC, laxitshahi commented on llmproxy/tests/unit_tests/llmproxy_client/test_llmproxy.py
>      assert "that is an apple" in output.response
This is not a unit test, it is an integration test

2024-01-20 07:11 UTC, laxitshahi commented on llmproxy/tests/unit_tests/llmproxy_client/test_llmproxy.py
> +        # NOTE: These are technically class functions; You should not be using them directly like this
Keep note of this; What excatly with this unit test? The use of the LLMProxy constructor or the individual functions?
You can of course test individual functions, but not like this; They need to be isolated and atomic, hence unit tests;

2024-01-20 07:11 UTC, laxitshahi commented on llmproxy/tests/unit_tests/llmproxy_client/test_llmproxy.py
> +        # NOTE: These are technically class functions; You should not be using them directly like this
Fix this issue in all the tests; Remember you are testing specific functionality; You are not trying to recreate the functionality in your unit and test that; At that point you are tesing your code, not the functionality in the code that exists.

2024-01-20 21:53 UTC, BallenAlain commented on llmproxy/tests/unit_tests/llmproxy_client/test_llmproxy.py
> +path_to_env_test = ".env.test"
This looks like this is unused since you're already specifying the env test path each time you call the constructor

2024-01-20 21:55 UTC, BallenAlain reviewed
Looks like some test are calling the functions directly and not initializing LLMProxy

2024-01-21 00:55 UTC, laxitshahi approved these changes

2024-01-21 00:55 UTC, merged