Proficiency routing
llm-proxy/llm-proxy pull request #211
Opened 2024-03-29 01:52 UTC by BallenAlain

resolves #195

2024-03-29 01:52 UTC, BallenAlain commented on proxyllm/proxyllm.py
> -            model_costs = {}
not being used anywhere

2024-03-29 01:53 UTC, BallenAlain commented on proxyllm/proxyllm.py
> +def _setup_model_data(settings: List[Dict[str, Any]]) -> Dict[str, Any]:
repurposed function to get model data from yml for both cost and proficiency routing

2024-03-29 05:03 UTC, laxitshahi requested changes
I will look at this review again after claude has been merged in

2024-03-29 05:03 UTC, laxitshahi commented on proxyllm/proxyllm.py
> +        logger.log(msg="Sorting fetched models based on elo rating...", color="GEEN")
typro

2024-03-29 18:21 UTC, BallenAlain commented on proxyllm/proxyllm.py
> +        logger.log(msg="Sorting fetched models based on elo rating...", color="GEEN")
fixed

2024-03-29 18:22 UTC, BallenAlain commented on proxyllm/proxyllm.py
>              )
relative ranking? elo is basically ranking but relative to each other

2024-03-30 19:22 UTC, laxitshahi requested changes
You need to add the route type to the literal:
![image](https://github.com/llm-proxy/llm-proxy/assets/46412618/df871d13-2251-4f3d-b415-6a4276debcf2)
To avoid this error:
![image](https://github.com/llm-proxy/llm-proxy/assets/46412618/678fdc5f-79e3-4a1a-8ac7-7cdd430424ed)

--
claude was merged in, so you will have to add that elo for that and make sure the routing makes sense

2024-03-30 21:05 UTC, BallenAlain commented
> You need to add the route type to the literal: ![image](https://private-user-images.githubusercontent.com/46412618/318219249-df871d13-2251-4f3d-b415-6a4276debcf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MzI4NTIsIm5iZiI6MTcxMTgzMjU1MiwicGF0aCI6Ii80NjQxMjYxOC8zMTgyMTkyNDktZGY4NzFkMTMtMjI1MS00ZjNkLWI0MTUtNmE0Mjc2ZGViY2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDIxMDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZGU4MTg2ZTJhYjFmYjJkOTVlOTljYWQ1NTA5MDQ5ZTAzNzFiNmMwNTJhNzZlYjA3MDBmZmE0NjhiZDFiNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wRGmvOiz-d_XMLkLKLMMHMmrX9fsqGhm9rLIDitfMDk) To avoid this error: ![image](https://private-user-images.githubusercontent.com/46412618/318219261-678fdc5f-79e3-4a1a-8ac7-7cdd430424ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MzI4NTIsIm5iZiI6MTcxMTgzMjU1MiwicGF0aCI6Ii80NjQxMjYxOC8zMTgyMTkyNjEtNjc4ZmRjNWYtNzllMy00YTFhLThhYzctN2NkZDQzMDQyNGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDIxMDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYjM4MWFhNTExNGQ1YTMyMWI3ZjQyZWQyOTQ3ZTgxYjg1ODdjMTFlYjZiMzNkOWU1NGQ1NmM4YzRmYjhmMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.13dDPQ8O5Hr42Ic0rheHnhbaJOK4lxq_70wu76FBtiE)
> 
> -- claude was merged in, so you will have to add that elo for that and make sure the routing makes sense

done

2024-03-31 16:30 UTC, BallenAlain commented on proxyllm/proxyllm.py
>              )
renamed to elo

2024-03-31 16:30 UTC, BallenAlain commented on proxyllm/proxyllm.py
> +                    msg="========PROFICIENCY ROUTING FAILED!===========\n",
will address in another PR (deprecating category routing)

2024-03-31 16:30 UTC, BallenAlain commented on proxyllm/config/internal_config.py
>                  "name": "gpt-4-1106-preview",
done

2024-03-31 16:52 UTC, BallenAlain commented on proxyllm/config/internal_config.py
> +                "elo": 0,
see comments and pr descriptino

2024-03-31 23:28 UTC, laxitshahi approved these changes

2024-03-31 23:28 UTC, merged